# Generated by Django 4.1.7 on 2023-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redactor',
            options={'ordering': ['username']},
        ),
        migrations.RenameField(
            model_name='newspaper',
            old_name='publishers',
            new_name='redactors',
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
