# Generated by Django 4.1.7 on 2023-04-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_redactor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaper',
            old_name='published_date',
            new_name='publication_date',
        ),
    ]
